#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX 

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Chromium desktop='^2'
bspc rule -a discord desktop='^3'
bspc rule -a Steam desktop='^4'
bspc rule -a PolyMC desktop='^4'
bspc rule -a spotify desktop='^5'
bspc rule -a Screenkey manage=off
# Border
bspc config focused_border_color        "#fcba03"
bspc config normal_border_color         "#8314e3"
bspc config active_border_color         "#8314e3"
$Autostart
picom -CGb --no-fading-openclose &
nitrogen --restore &
nm-applet --indicatior &
usr/bin/dunst &
polybar
